name: "Run Tests"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        dependencies:
          - "lowest"
          - "highest"

    steps:
    - uses: actions/checkout@v3

    - name: "Install PHP"
      uses: "shivammathur/setup-php@2.26.0"
      with:
        php-version: "${{ matrix.php-version }}"

    - name: "Validate composer.json"
      run: composer validate --strict

    - name: "Install dependencies (Composer)"
      uses: "ramsey/composer-install@2.2.0"
      with:
        dependency-versions: "${{ matrix.dependencies }}"

    - name: "Run test suite"
      run: composer test
